doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        logging: false
        profiling: false

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        report_fields_where_declared: true
        enable_lazy_ghost_objects: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Application/Entity'
                prefix: 'App\Application\Entity'
                alias: App
            Region:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Region/Entity'
                prefix: 'App\Region\Entity'
                alias: Region
            SubRegion:
                is_bundle: false
                dir: '%kernel.project_dir%/src/SubRegion/Entity'
                prefix: 'App\SubRegion\Entity'
                alias: SubRegion
            Timezone:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Timezone/Entity'
                prefix: 'App\Timezone\Entity'
                alias: Timezone
            Currency:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Currency/Entity'
                prefix: 'App\Currency\Entity'
                alias: Currency
            Country:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Country/Entity'
                prefix: 'App\Country\Entity'
                alias: Country
            State:
                is_bundle: false
                dir: '%kernel.project_dir%/src/State/Entity'
                prefix: 'App\State\Entity'
                alias: State
            City:
                is_bundle: false
                dir: '%kernel.project_dir%/src/City/Entity'
                prefix: 'App\City\Entity'
                alias: City
            Airport:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Airport/Entity'
                prefix: 'App\Airport\Entity'
                alias: Airport
            Nationality:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Nationality/Entity'
                prefix: App\Nationality\Entity
                alias: Nationality

when@test:
    doctrine:
        dbal:
            url: '%env(resolve:DATABASE_URL)%'
            logging: false
            profiling: false

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
