monolog:
  channels:
    - deprecation

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: php://stderr
        level: debug
        channels: ["!event", "!doctrine"]
      security:
        type: stream
        path: php://stderr
        level: error
        channels: ["security"]
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr

when@test:
  monolog:
    handlers:
      nested:
        type: stream
        path: php://stderr
        level: info
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]

when@stage:
  monolog:
    handlers:
      rollbar:
        type: service
        id: Rollbar\Monolog\Handler\RollbarHandler
      main:
        type: fingers_crossed
        path: php://stderr
        handler: rollbar
        excluded_http_codes: [404, 403, 405]
        level: debug
        channels: ["!event", "!doctrine", "!console", "!security", "!request"]
      security:
        type: stream
        path: php://stderr
        level: error
        channels: ["security"]
      nested:
        type: stream
        path: php://stderr
        level: info
        formatter: monolog.formatter.json
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr

when@prod:
  monolog:
    handlers:
      rollbar:
        type: service
        id: Rollbar\Monolog\Handler\RollbarHandler
      main:
        type: fingers_crossed
        path: php://stderr
        handler: rollbar
        excluded_http_codes: [404, 403, 405]
        level: debug
        channels: ["!event", "!doctrine", "!console", "!security", "!request"]
      nested:
        type: stream
        path: php://stderr
        level: info
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr
