nelmio_api_doc:
    areas:
        path_patterns: [ ^/api/ ]
    documentation:
        servers:
          - url: http://127.0.0.1:8085
            description: Local environment
        info:
            title: GeoService API
            version: 2.2.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
