version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  relay: pipes
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:${RR_HTTP_PORT:-8080}
  pool:
    debug: false
    num_workers: ${RR_NUM_WORKERS:-3}
    supervisor:
      max_worker_memory: ${RR_WORKER_MAX_MEMORY:-75}
  middleware: ["static", "gzip"]
  static:
    dir: "public"
    forbid: [".php"]
  ssl:
    address: 0.0.0.0:443
    redirect: true
    key: ${RR_SSL_CERT_KEY}
    cert: ${RR_SSL_CERT_CRT}
    acme:
      certs_dir: ${RR_SSL_CERT_DIR:-.cert}
      email: ${RR_SSL_EMAIL}
      alt_http_port: 80
      alt_tlsalpn_port: 443
      challenge_type: http-01
      use_production_endpoint: true
      domains:
        - ${RR_SSL_DOMAIN}

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
