version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  relay: pipes
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:${RR_HTTP_PORT:-8080}
  pool:
    debug: false
    num_workers: ${RR_NUM_WORKERS:-3}
    supervisor:
      max_worker_memory: ${RR_WORKER_MAX_MEMORY:-75}
  middleware: ["static", "gzip"]
  static:
    dir: "public"
    forbid: [".php"]

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
