version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    num_workers: ${APP_NUM_WORKERS:-2}
    max_jobs: 100
    supervisor:
      max_worker_memory: 75
  middleware: [ "static", "gzip" ]
  static:
    dir: "public"
    forbid: [ ".php" ]

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
