version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  relay: pipes
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  pool:
    debug: false
    allocate_timeout: 10s
    max_queue_size: 32
    max_jobs: 1000
    num_workers: 6
    supervisor:
      max_worker_memory: 100
      ttl: 7200s
  middleware: ["static", "gzip"]
  static:
    dir: "public"
    forbid: [".php"]

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
