version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
    - XDEBUG_SESSION: '1'

http:
  address: 0.0.0.0:${RR_HTTP_PORT:-8080}
  middleware: [ "static", "gzip" ]
  pool:
    num_workers: ${RR_NUM_WORKERS:-3}
    debug: true
  static:
    dir: "public"
    forbid: [ ".php" ]

logs:
  mode: development
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
