version: "3"

networks:
  geo-service-network:


services:
  geo-service-app:
    build:
      context: .
      dockerfile: .docker/php/dev.Dockerfile
    container_name: geo-service-app-dev
    working_dir: /var/www/geo-service
    ports:
      - "8085:8080"
    volumes:
      - .:/var/www/geo-service
      - .docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - geo-service-network

  geo-service-db:
    image: mariadb:11.3
    container_name: geo-service-db
    ports:
      - "5306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_USER: ${DB_USER:-geo-service}
      MYSQL_DATABASE: ${DB_DATABASE:-geo-service}
    volumes:
      - geo-service-db-data:/var/lib/mysql
    networks:
      - geo-service-network

volumes:
  geo-service-db-data:
