version: "3"

networks:
  geo-service-network:


services:
  geo-service-nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/geo-service
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - geo-service-app
      - geo-service-db
    networks:
      - geo-service-network

  geo-service-app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www/geo-service
      - .docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - geo-service-network

  geo-service-db:
    image: mariadb:10.9.3
    container_name: db
    ports:
      - "5306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_PASSWORD: ${DB_PASSWORD:-qwerty}
      MYSQL_USER: ${DB_USER:-geo-service}
      MYSQL_DATABASE: ${DB_DATABASE:-geo-service}
    networks:
      - geo-service-network
