controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_regions:
  resource:
    path: ../src/Region/Controller/
    namespace: App\Region\Controller
  type: attribute

app_subregions:
  resource:
    path: ../src/SubRegion/Controller/
    namespace: App\SubRegion\Controller
  type: attribute

app_timezones:
  resource:
    path: ../src/Timezone/Controller/
    namespace: App\Timezone\Controller
  type: attribute

app_currencies:
  resource:
    path: ../src/Currency/Controller/
    namespace: App\Currency\Controller
  type: attribute

app_countries:
  resource:
    path: ../src/Country/Controller/
    namespace: App\Country\Controller
  type: attribute