controllers:
  resource:
    path: ../src/Application/Controller/
    namespace: App\Application\Controller
  type: attribute

app.swagger:
    path: /apidoc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
   path: /apidoc
   methods: GET
   defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app_nationalities:
  resource:
    path: ../src/Nationality/Controller
    namespace: App\Nationality\Controller
  type: attribute

app_regions:
  resource:
    path: ../src/Region/Controller/
    namespace: App\Region\Controller
  type: attribute

app_subregions:
  resource:
    path: ../src/SubRegion/Controller/
    namespace: App\SubRegion\Controller
  type: attribute

app_timezones:
  resource:
    path: ../src/Timezone/Controller/
    namespace: App\Timezone\Controller
  type: attribute

app_currencies:
  resource:
    path: ../src/Currency/Controller/
    namespace: App\Currency\Controller
  type: attribute

app_countries:
  resource:
    path: ../src/Country/Controller/
    namespace: App\Country\Controller
  type: attribute

app_states:
  resource:
    path: ../src/State/Controller/
    namespace: App\State\Controller
  type: attribute

app_cities:
  resource:
    path: ../src/City/Controller/
    namespace: App\City\Controller
  type: attribute

app_airports:
  resource:
    path: ../src/Airport/Controller/
    namespace: App\Airport\Controller
  type: attribute
