parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/*/Entity/"
      - "../src/Kernel.php"

  App\Application\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Application\EventListener\TokenSubscriber:
    arguments:
      $apiAuthToken: "%env(API_AUTH_TOKEN)%"
      $apiAuthEnabled: "%env(bool:API_AUTH_ENABLED)%"
    tags:
      - { name: kernel.event_subscriber }
